### ISSUE TITLE
你好，最直接的就是 feature 下的所有模块的 build.gradle 都是空空如也？

### ISSUE THREAD

**Issue by cervy** [Blankj/AucFrameTemplate#2]
你好，假如pkg或mock需要各自单独的依赖， 请问 是要手动把所有依赖都下沉到base module里吗，还是通过 您的以下脚本自动依赖了isApply=true的库啊？
/**
         * 根据 depConfig 生成 dep
         */
        private static generateDep(Gradle gradle) {
            def config = getDepConfigByFilter(new DepConfigFilter() {
                @Override
                boolean accept(String name, DepConfig config) {
                    if (config.useLocal) {// 如果使用的是本地模块，那么把它转化为 project
                        config.dep = gradle.rootProject.findProject(config.localPath)
                    } else {// 如果是远端依赖，那就直接使用远端依赖即可
                        config.dep = config.remotePath
                    }
                    return true
                }
            })
            GLog.l("generateDep = ${GLog.object2String(config)}")
        }
因为只看到这段改了下路径并没有调用 api/implementation，对groovy不太熟，所以产生了以上疑惑。多谢解惑~

**Comment by Blankj** [comment]
pkg 所有依赖的 sdk 都放到 lib 下即可，lib 中通过 common 来汇集到一起就行，然后全量提供给上层 pkg 即可，免去了以后修改 pkg 依赖的麻烦，也免去了后期如果多个 pkg 都依赖同一个 lib 然后还是下沉到 common 的必要。

**Comment by cervy** [comment]
不过这样会不会有个弊端，因为api 和 bus插件目前在编译期耗时有点大，全放common里，若pkg没全量使用common或少量使用，插件扫描全量common的时间会不会多余了呢
