### ISSUE TITLE
Gradle 6.0  Build Error

### ISSUE THREAD

**Issue by Toaok** [Blankj/AucFrameTemplate#5]
* Where:
Settings file 'E:\AucFrameTemplate-master\settings.gradle' line: 1

* What went wrong:
A problem occurred evaluating settings 'AucFrameTemplate-master'.
> Could not get unknown property 'ConfigUtils' for settings 'AucFrameTemplate-master' of type org.gradle.initialization.DefaultSettings.

**Comment by Blankj** [comment]
已解决
