### ISSUE TITLE
编译时间很慢

### ISSUE THREAD

**Issue by BelongsH** [Blankj/AucFrameTemplate#8]
在看完`AUC`的文档之后，打算把自己的项目使用这种方式来进行构建。但是在构建中的过程中发现了一个问题。

不管是有没有改代码，每次编译的时间都很慢。（调试起来很不方便）

之前的项目，第一次运行的时候很慢，但接下来运行的时间就很快。（调试起来就很方便）

因为`ARouter`的问题，所以更改了`module`的名称，更改方式是
```
project(proPath).projectDir = new File(".${pro.localPath.replace(":", "/")}")
```
我怀疑是这个的问题

不知道是否有人遇到过，或者有更好的处理方式

**Comment by Blankj** [comment]
这个已经在文档里更新做了优化了哈
